# Chapter 5 - Background on Regression Modeling

```{r}
# Set up libraries and functions
library(tidyverse)
library(rosdata)
library(rstanarm)
library(patchwork)
options(mc.cores = parallel::detectCores())
```

```{r}
x <- 1:20
n <- length(x)
a <- 0.2
b <- 0.3
sigma <- 0.5
y <- a + b*x + sigma*rnorm(n)

plot(x, y)
```

```{r}
fake <- tibble(x, y)

fit1 <- stan_glm(y ~ x, data = fake)

print(fit1, digits=2)

```

```{r}
plot(fake$x, fake$y, main="Data and fitted regression line")
a_hat <- coef(fit1)[1]
b_hat <- coef(fit1)[2]
abline(a_hat, b_hat)
x_bar <- mean(fake$x)
text(x_bar, a_hat + b_hat*x_bar,
paste("y =", round(a_hat, 2), "+", round(b_hat, 2), "* x"), adj=0)
```

```{r}
earnings$earnk <- earnings$earn/1000
fit_2 <- stan_glm(earnk ~ height + male, data=earnings)
print(fit_2)
```

```{r}
R2 <- 1 - sigma(fit_2)^2 / sd(earnings$earnk)^2
R2
```

```{r}
print(heights[1:5,])

fit_1 <- stan_glm(daughter_height ~ mother_height, data=heights)
print(fit_1)
```

```{r}
n <- nrow(heights)
mother_height_jitt <- heights$mother_height + runif(n, -0.5, 0.5)
daughter_height_jitt <- heights$daughter_height + runif(n, -0.5, 0.5)
plot(mother_height_jitt, daughter_height_jitt, xlab="Mother's height (inches)",
ylab="Adult daughter's height (inches)")
a_hat <- coef(fit_1)[1]
b_hat <- coef(fit_1)[2]
abline(a_hat, b_hat)
```

```{r}
n <- 1000
true_ability <- rnorm(n, 50, 10)
noise_1 <- rnorm(n, 0, 10)
noise_2 <- rnorm(n, 0, 10)
midterm <- true_ability + noise_1
final <- true_ability + noise_2
exams <- tibble(midterm, final)
```

```{r}
fit_1 <- stan_glm(final ~ midterm, data=exams)
plot(midterm, final, xlab="Midterm exam score", ylab="Final exam score")
abline(coef(fit_1))
```

# Exercises

## 2.)

```{r}
# Function
sim_data_points <- function(n = 1000, sigma = 10, a, b) {
    x <- runif(n, min = 0, max = 100)
    errors <- rnorm(n, mean = 0, sd = sigma)
    y = a + b*x + errors
    
    dat = tibble(y, x)
    
    # Fit model
    mod <- stan_glm(y ~ x, data = dat)
    
    # Scatterplot
    plot(x, y, xlab="X", ylab="Y")
    abline(coef(mod))
}

sim_data_points(100, sigma = 10, a = 200, b = 1)
```

## 3.)

```{r}
# Function
sim_data_points <- function(n = 1000, sigma = 10, a, b) {
    x <- runif(n, min = 0, max = 100)
    errors <- rnorm(n, mean = 0, sd = sigma)
    y = a + b*x + errors
    
    dat = tibble(y, x)
    
    # Fit model
    mod <- stan_glm(y ~ x, data = dat)
    
    # Return model
    se(mod)
}

sim_data_points(100, sigma = 100, a = 10, b = 5) -> a
```

## 4.)

```{r}
seq <- c(10, 20, 100, 500, 1000, 10000)
    
# Function
sim_data_points <- function(n, sigma = 10, a = 10, b = 5) {
    x <- runif(n, min = 0, max = 100)
    errors <- rnorm(n, mean = 0, sd = sigma)
    y = a + b*x + errors
    
    dat = tibble(y, x)
    
    # Fit model
    mod <- stan_glm(y ~ x, data = dat)
    
    # Return results
    tibble(sims = n, se_for_slope = se(mod)[2])
}

# Map over sequence
results <- map(seq, sim_data_points)

results <- bind_rows(results)

results |> 
    ggplot(aes(x = sims, y = se_for_slope)) +
    geom_point()
```

## 5.)

```{r}
earnings |> 
    group_by(male) |> 
    summarise(avg_height_male = mean(height))
```

```{r}
mod <- stan_glm(earn ~ height + male, data=earnings)
print(mod)
```

Average earnings for men: -25915.8 + 649.2*70.08889 + 10618.9 = 30,204.81
Average earnings for women: -25915.8 + 649.2*64.48642 = 15,948.78

Average earnings for population: 0.52 * 15948.78 + 0.48 * 30204.81 = 22,791.67

```{r}
earnings |> 
    group_by(male) |> 
    summarise(avg_earnings = mean(earn))
```

```{r}
earnings |> 
    summarise(avg_earnings = mean(earn))
```
The estimates are slightly different, but very close to each other.
